local fixture = require("tests.support.charge_release_fixture")

describe("weapon identity refresh", function()
    it("resolves a ranged secondary and a melee primary", function()
        local f = fixture("none", 100, 50)
        assert.are.equal("RANGED", f.weapon:weapon_type())
        assert.are.equal("forcestaff_p2_m1", f.weapon:weapon_name())

        f.equip("slot_primary", "content/items/weapons/player/melee/combatsword_p1_m1")
        f.weapon:refresh_weapon()
        assert.are.equal("MELEE", f.weapon:weapon_type())
        assert.are.equal("combatsword_p1_m1", f.weapon:weapon_name())
    end)

    it("updates the name again after several weapon changes", function()
        local f = fixture("none", 100, 50)
        f.equip("slot_primary", "content/items/weapons/player/melee/combatsword_p1_m1")
        f.weapon:refresh_weapon()
        f.equip("slot_secondary", "content/items/weapons/player/ranged/lasgun_p1_m1")
        f.weapon:refresh_weapon()
        assert.are.equal("RANGED", f.weapon:weapon_type())
        assert.are.equal("lasgun_p1_m1", f.weapon:weapon_name())

        f.equip("slot_primary", "content/items/weapons/player/melee/powermaul_p2_m1")
        f.weapon:refresh_weapon()
        assert.are.equal("MELEE", f.weapon:weapon_type())
        assert.are.equal("powermaul_p2_m1", f.weapon:weapon_name())
    end)

    it("still treats psyker throwing knives as ranged in the ability slot", function()
        local f = fixture("none", 100, 50)
        f.equip("slot_grenade_ability", "content/items/weapons/player/ranged/psyker_throwing_knives")
        f.weapon:refresh_weapon()
        assert.are.equal("RANGED", f.weapon:weapon_type())
        assert.are.equal("psyker_throwing_knives", f.weapon:weapon_name())
    end)

    it("does not treat an ordinary ability as ranged", function()
        local f = fixture("none", 100, 50)
        f.equip("slot_grenade_ability", "content/items/weapons/player/grenades/frag_grenade")
        f.weapon:refresh_weapon()
        assert.are_not.equal("RANGED", f.weapon:weapon_type())
    end)
end)
